# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheMovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMovieApp
	pod 'Alamofire'

  target 'TheMovieAppTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Alamofire'

  end

  target 'TheMovieAppUITests' do
    # Pods for testing
	pod 'Alamofire'

  end

end

target 'TheMovieApp-dev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMovieApp-dev
	pod 'Alamofire'

end
